### ISSUE TITLE
请问safari 全能搜索怎么用

### ISSUE THREAD

**Issue by lzx-dot** [TributePaulWalker/Profiles#4]
导入本地重写后，在safari 搜索框输入代号加空格，然后输入搜索内容，这种行不通

**Comment by Ymshub** [comment]
> 导入本地重写后，在safari 搜索框输入代号加空格，然后输入搜索内容，这种行不通

首先吧Safari的搜索引擎改为DuckDuckGo，这样输入代号才会有用。

**Comment by TributePaulWalker** [comment]
> 导入本地重写后，在safari 搜索框输入代号加空格，然后输入搜索内容，这种行不通

配置注释写的很清楚，需要把Safari的搜索引擎改为DuckDuckGo
